#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';


use Dotenv\Dotenv;
use NovaSysCore\Config;
use NovaSysCore\Database\Migrator;


$dotenv = Dotenv::createImmutable(
    __DIR__
);

$dotenv->load();


Config::load(
    'database',
    __DIR__ . '/config/database.php'
);

$command = $argv[1] ?? null;


switch ($command) {


    case 'migrate':

        $migrator = new Migrator();

        $migrator->run();

        echo "Migraciones ejecutadas correctamente 🚀" . PHP_EOL;

        break;



    case 'rollback':

        $migrator = new Migrator();

        $migrator->rollback();

        echo "Rollback ejecutado correctamente 🚀" . PHP_EOL;

        break;



    default:

        echo "NovaSysCore Console" . PHP_EOL;

        echo "Comandos disponibles:" . PHP_EOL;

        echo "  migrate" . PHP_EOL;

        echo "  rollback" . PHP_EOL;

        break;

}